apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: me-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: aethelred-validator
            namespace: aethelred-mainnet
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aethelred-validator-secrets
  namespace: aethelred-mainnet
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: aethelred-validator-keys
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: validator_key.json
      remoteRef:
        key: /aethelred/mainnet/validator
        property: validator_key.json
    - secretKey: node_key.json
      remoteRef:
        key: /aethelred/mainnet/validator
        property: node_key.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aethelred-tee-secrets
  namespace: aethelred-mainnet
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: aethelred-tee-keys
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: tee_private_key.pem
      remoteRef:
        key: /aethelred/mainnet/tee
        property: tee_private_key.pem
