apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aethelred-validator-spc
  namespace: aethelred-mainnet
spec:
  provider: aws
  parameters:
    region: me-central-1
    objects: |
      - objectName: /aethelred/mainnet/validator
        objectType: secretsmanager
      - objectName: /aethelred/mainnet/tee
        objectType: secretsmanager
  secretObjects:
    - secretName: aethelred-validator-keys
      type: Opaque
      data:
        - objectName: /aethelred/mainnet/validator
          key: validator_bundle.json
    - secretName: aethelred-tee-keys
      type: Opaque
      data:
        - objectName: /aethelred/mainnet/tee
          key: tee_bundle.json
