apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-aethelred
spec:
  provider:
    vault:
      server: https://vault.aethelred.internal
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: aethelred-validator-role
          serviceAccountRef:
            name: aethelred-validator
            namespace: aethelred-mainnet
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aethelred-validator-secrets-vault
  namespace: aethelred-mainnet
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-aethelred
  target:
    name: aethelred-validator-keys
    creationPolicy: Owner
  data:
    - secretKey: validator_key.json
      remoteRef:
        key: aethelred/mainnet/validator
        property: validator_key.json
    - secretKey: node_key.json
      remoteRef:
        key: aethelred/mainnet/validator
        property: node_key.json
