/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IVaultTEEVerifierUpgraderTimelockDelaySource, IVaultTEEVerifierUpgraderTimelockDelaySourceInterface } from "../../../../contracts/vault/VaultTEEVerifier.sol/IVaultTEEVerifierUpgraderTimelockDelaySource.js";

  const _abi = [
  {
    "inputs": [],
    "name": "getMinDelay",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IVaultTEEVerifierUpgraderTimelockDelaySource__factory {
    static readonly abi = _abi;
    static createInterface(): IVaultTEEVerifierUpgraderTimelockDelaySourceInterface {
      return new Interface(_abi) as IVaultTEEVerifierUpgraderTimelockDelaySourceInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IVaultTEEVerifierUpgraderTimelockDelaySource {
      return new Contract(address, _abi, runner) as unknown as IVaultTEEVerifierUpgraderTimelockDelaySource;
    }
  }
  