//! Software Bill of Materials (SBOM) tracking per service version.
//!
//! NIST SSDF, EU Cyber Resilience Act, and US EO 14028 require organizations
//! to maintain SBOMs for every shipped service version. This module is the
//! canonical store: per service version, the list of dependencies with
//! versions and known CVEs.

use crate::hashing::{Hasher, Sha256Digest};
use crate::{SandboxError, SandboxResult};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::sync::RwLock;
use time::OffsetDateTime;
use uuid::Uuid;

// =============================================================================
// SbomFormat
// =============================================================================

/// Standard SBOM format reference.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SbomFormat {
    /// CycloneDX 1.5+.
    CycloneDx,
    /// SPDX 2.3+.
    Spdx,
    /// SWID.
    Swid,
}

// =============================================================================
// VulnSeverity
// =============================================================================

/// Vulnerability severity (CVSS v3 bands).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VulnSeverity {
    /// 9.0–10.0.
    Critical,
    /// 7.0–8.9.
    High,
    /// 4.0–6.9.
    Medium,
    /// 0.1–3.9.
    Low,
    /// Informational.
    None,
}

// =============================================================================
// Vulnerability
// =============================================================================

/// One known CVE.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Vulnerability {
    /// CVE id (e.g. `"CVE-2024-12345"`).
    pub cve_id: String,
    /// Severity.
    pub severity: VulnSeverity,
    /// CVSS score.
    pub cvss: Option<f64>,
    /// Optional fix version.
    pub fix_version: Option<String>,
    /// Free-text description.
    pub description: String,
}

// =============================================================================
// Component
// =============================================================================

/// One SBOM component.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Component {
    /// Stable id (e.g. `"pkg:cargo/serde@1.0.193"`).
    pub purl: String,
    /// Name.
    pub name: String,
    /// Version.
    pub version: String,
    /// License.
    pub license: Option<String>,
    /// Hash of binary if known.
    pub content_hash: Option<Sha256Digest>,
    /// Known vulnerabilities.
    pub vulnerabilities: Vec<Vulnerability>,
}

impl Component {
    /// `true` if any critical or high vuln present.
    pub fn has_high_or_critical(&self) -> bool {
        self.vulnerabilities
            .iter()
            .any(|v| matches!(v.severity, VulnSeverity::Critical | VulnSeverity::High))
    }
    /// Highest severity present.
    pub fn highest_severity(&self) -> Option<VulnSeverity> {
        self.vulnerabilities
            .iter()
            .map(|v| v.severity)
            .min_by_key(|s| sev_rank(*s))
    }
}

fn sev_rank(s: VulnSeverity) -> u8 {
    match s {
        VulnSeverity::Critical => 0,
        VulnSeverity::High => 1,
        VulnSeverity::Medium => 2,
        VulnSeverity::Low => 3,
        VulnSeverity::None => 4,
    }
}

// =============================================================================
// Sbom
// =============================================================================

/// One SBOM record for a service version.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Sbom {
    /// Stable id.
    pub sbom_id: Uuid,
    /// Service name (e.g. `"sandbox-finance"`).
    pub service_id: String,
    /// Service version.
    pub service_version: String,
    /// Format.
    pub format: SbomFormat,
    /// Components.
    pub components: Vec<Component>,
    /// Aggregate hash of all component purls + versions.
    pub aggregate_hash: Sha256Digest,
    /// RFC 3339 generated.
    pub generated_at: String,
    /// Generated by.
    pub generated_by: String,
}

impl Sbom {
    /// Components with critical or high vulns.
    pub fn vulnerable_components(&self) -> Vec<&Component> {
        self.components.iter().filter(|c| c.has_high_or_critical()).collect()
    }
    /// Total vulnerability count.
    pub fn total_vulnerabilities(&self) -> usize {
        self.components.iter().map(|c| c.vulnerabilities.len()).sum()
    }
    /// Unique licenses present.
    pub fn unique_licenses(&self) -> HashSet<String> {
        self.components
            .iter()
            .filter_map(|c| c.license.clone())
            .collect()
    }
}

fn compute_aggregate_hash(components: &[Component]) -> Sha256Digest {
    let mut buf = Vec::new();
    for c in components {
        buf.extend_from_slice(c.purl.as_bytes());
        buf.push(0);
    }
    Hasher::sha256(&buf)
}

// =============================================================================
// SbomRegistry
// =============================================================================

#[derive(Default)]
struct State {
    sboms: HashMap<Uuid, Sbom>,
    by_service: HashMap<(String, String), Uuid>,
}

/// Registry.
pub struct SbomRegistry {
    state: RwLock<State>,
}

impl Default for SbomRegistry {
    fn default() -> Self {
        Self {
            state: RwLock::new(State::default()),
        }
    }
}

impl std::fmt::Debug for SbomRegistry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SbomRegistry")
            .field("sboms", &self.len())
            .finish()
    }
}

impl SbomRegistry {
    /// New empty.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register an SBOM (replaces any existing for `service_version`).
    pub fn register(
        &self,
        service_id: impl Into<String>,
        service_version: impl Into<String>,
        format: SbomFormat,
        components: Vec<Component>,
        generated_by: impl Into<String>,
    ) -> SandboxResult<Sbom> {
        let service_id = service_id.into();
        let service_version = service_version.into();
        let aggregate = compute_aggregate_hash(&components);
        let s = Sbom {
            sbom_id: Uuid::now_v7(),
            service_id: service_id.clone(),
            service_version: service_version.clone(),
            format,
            components,
            aggregate_hash: aggregate,
            generated_at: OffsetDateTime::now_utc()
                .format(&time::format_description::well_known::Rfc3339)
                .unwrap_or_default(),
            generated_by: generated_by.into(),
        };
        let mut g = self
            .state
            .write()
            .map_err(|_| SandboxError::Other("sbom registry poisoned".into()))?;
        // Drop prior SBOM for the same (service, version) combination.
        if let Some(prior) = g.by_service.remove(&(service_id.clone(), service_version.clone())) {
            g.sboms.remove(&prior);
        }
        g.by_service.insert((service_id, service_version), s.sbom_id);
        g.sboms.insert(s.sbom_id, s.clone());
        Ok(s)
    }

    /// Look up by service id + version.
    pub fn for_service(&self, service: &str, version: &str) -> Option<Sbom> {
        let g = self.state.read().ok()?;
        let id = g.by_service.get(&(service.to_string(), version.to_string()))?;
        g.sboms.get(id).cloned()
    }

    /// Lookup by id.
    pub fn get(&self, id: Uuid) -> Option<Sbom> {
        self.state.read().ok()?.sboms.get(&id).cloned()
    }

    /// All SBOMs.
    pub fn all(&self) -> Vec<Sbom> {
        self.state
            .read()
            .map(|g| g.sboms.values().cloned().collect())
            .unwrap_or_default()
    }

    /// All SBOMs that contain a CVE id.
    pub fn affected_by_cve(&self, cve_id: &str) -> Vec<Sbom> {
        self.all()
            .into_iter()
            .filter(|s| {
                s.components
                    .iter()
                    .any(|c| c.vulnerabilities.iter().any(|v| v.cve_id == cve_id))
            })
            .collect()
    }

    /// All SBOMs that include a component by purl.
    pub fn services_using_component(&self, purl: &str) -> Vec<Sbom> {
        self.all()
            .into_iter()
            .filter(|s| s.components.iter().any(|c| c.purl == purl))
            .collect()
    }

    /// Count.
    pub fn len(&self) -> usize {
        self.state.read().map(|g| g.sboms.len()).unwrap_or(0)
    }
    /// Empty?
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn comp(purl: &str, name: &str, version: &str) -> Component {
        Component {
            purl: purl.into(),
            name: name.into(),
            version: version.into(),
            license: Some("Apache-2.0".into()),
            content_hash: None,
            vulnerabilities: Vec::new(),
        }
    }

    fn vuln(cve: &str, sev: VulnSeverity) -> Vulnerability {
        Vulnerability {
            cve_id: cve.into(),
            severity: sev,
            cvss: Some(7.5),
            fix_version: Some("1.0.5".into()),
            description: "x".into(),
        }
    }

    #[test]
    fn register_creates_sbom() {
        let r = SbomRegistry::new();
        let s = r
            .register(
                "sandbox-finance",
                "0.2.16",
                SbomFormat::CycloneDx,
                vec![comp("pkg:cargo/serde@1.0.193", "serde", "1.0.193")],
                "ci",
            )
            .unwrap();
        assert_eq!(s.components.len(), 1);
    }

    #[test]
    fn aggregate_hash_deterministic() {
        let c = vec![comp("a", "x", "1"), comp("b", "y", "1")];
        let h1 = compute_aggregate_hash(&c);
        let h2 = compute_aggregate_hash(&c);
        assert_eq!(h1, h2);
    }

    #[test]
    fn register_replaces_prior() {
        let r = SbomRegistry::new();
        let s1 = r
            .register(
                "x",
                "1",
                SbomFormat::CycloneDx,
                vec![comp("a", "a", "1")],
                "ci",
            )
            .unwrap();
        let _s2 = r
            .register(
                "x",
                "1",
                SbomFormat::CycloneDx,
                vec![comp("b", "b", "1")],
                "ci",
            )
            .unwrap();
        // First SBOM should be gone.
        assert!(r.get(s1.sbom_id).is_none());
        // Lookup by service should give the new one.
        let cur = r.for_service("x", "1").unwrap();
        assert_eq!(cur.components[0].purl, "b");
    }

    #[test]
    fn for_service_lookup() {
        let r = SbomRegistry::new();
        r.register("x", "1", SbomFormat::CycloneDx, vec![], "ci").unwrap();
        assert!(r.for_service("x", "1").is_some());
        assert!(r.for_service("x", "2").is_none());
    }

    #[test]
    fn vulnerable_components_filter() {
        let mut c = comp("a", "a", "1");
        c.vulnerabilities.push(vuln("CVE-1", VulnSeverity::Critical));
        let r = SbomRegistry::new();
        let s = r
            .register("x", "1", SbomFormat::CycloneDx, vec![c], "ci")
            .unwrap();
        assert_eq!(s.vulnerable_components().len(), 1);
    }

    #[test]
    fn high_or_critical_classification() {
        let mut c = comp("a", "a", "1");
        c.vulnerabilities.push(vuln("CVE-1", VulnSeverity::Low));
        assert!(!c.has_high_or_critical());
        c.vulnerabilities.push(vuln("CVE-2", VulnSeverity::High));
        assert!(c.has_high_or_critical());
    }

    #[test]
    fn highest_severity_picks_critical() {
        let mut c = comp("a", "a", "1");
        c.vulnerabilities.push(vuln("CVE-low", VulnSeverity::Low));
        c.vulnerabilities.push(vuln("CVE-crit", VulnSeverity::Critical));
        c.vulnerabilities.push(vuln("CVE-high", VulnSeverity::High));
        assert_eq!(c.highest_severity(), Some(VulnSeverity::Critical));
    }

    #[test]
    fn affected_by_cve_filters() {
        let r = SbomRegistry::new();
        let mut c = comp("a", "a", "1");
        c.vulnerabilities.push(vuln("CVE-1", VulnSeverity::Critical));
        r.register("x", "1", SbomFormat::CycloneDx, vec![c], "ci").unwrap();
        let affected = r.affected_by_cve("CVE-1");
        assert_eq!(affected.len(), 1);
        assert!(r.affected_by_cve("CVE-99").is_empty());
    }

    #[test]
    fn services_using_component() {
        let r = SbomRegistry::new();
        r.register(
            "service-a",
            "1",
            SbomFormat::CycloneDx,
            vec![comp("pkg:cargo/serde@1.0.193", "serde", "1.0.193")],
            "ci",
        )
        .unwrap();
        r.register(
            "service-b",
            "1",
            SbomFormat::CycloneDx,
            vec![comp("pkg:cargo/tokio@1.0", "tokio", "1.0")],
            "ci",
        )
        .unwrap();
        assert_eq!(
            r.services_using_component("pkg:cargo/serde@1.0.193").len(),
            1
        );
    }

    #[test]
    fn unique_licenses_collected() {
        let mut c1 = comp("a", "a", "1");
        let mut c2 = comp("b", "b", "1");
        c1.license = Some("Apache-2.0".into());
        c2.license = Some("MIT".into());
        let r = SbomRegistry::new();
        let s = r
            .register("x", "1", SbomFormat::CycloneDx, vec![c1, c2], "ci")
            .unwrap();
        let licenses = s.unique_licenses();
        assert_eq!(licenses.len(), 2);
    }

    #[test]
    fn total_vulnerabilities_sums() {
        let mut c1 = comp("a", "a", "1");
        c1.vulnerabilities.push(vuln("CVE-1", VulnSeverity::High));
        c1.vulnerabilities.push(vuln("CVE-2", VulnSeverity::Low));
        let r = SbomRegistry::new();
        let s = r
            .register("x", "1", SbomFormat::CycloneDx, vec![c1], "ci")
            .unwrap();
        assert_eq!(s.total_vulnerabilities(), 2);
    }

    #[test]
    fn sbom_serde() {
        let r = SbomRegistry::new();
        let s = r
            .register("x", "1", SbomFormat::CycloneDx, vec![comp("a", "a", "1")], "ci")
            .unwrap();
        let j = serde_json::to_string(&s).unwrap();
        let p: Sbom = serde_json::from_str(&j).unwrap();
        assert_eq!(p, s);
    }

    #[test]
    fn component_serde() {
        let c = comp("a", "a", "1");
        let j = serde_json::to_string(&c).unwrap();
        let p: Component = serde_json::from_str(&j).unwrap();
        assert_eq!(p, c);
    }

    #[test]
    fn vulnerability_serde() {
        let v = vuln("CVE-1", VulnSeverity::High);
        let j = serde_json::to_string(&v).unwrap();
        let p: Vulnerability = serde_json::from_str(&j).unwrap();
        assert_eq!(p, v);
    }

    #[test]
    fn format_serde() {
        for f in [SbomFormat::CycloneDx, SbomFormat::Spdx, SbomFormat::Swid] {
            let j = serde_json::to_string(&f).unwrap();
            let p: SbomFormat = serde_json::from_str(&j).unwrap();
            assert_eq!(p, f);
        }
    }

    #[test]
    fn severity_serde() {
        for s in [
            VulnSeverity::Critical,
            VulnSeverity::High,
            VulnSeverity::Medium,
            VulnSeverity::Low,
            VulnSeverity::None,
        ] {
            let j = serde_json::to_string(&s).unwrap();
            let p: VulnSeverity = serde_json::from_str(&j).unwrap();
            assert_eq!(p, s);
        }
    }

    #[test]
    fn registry_count_tracks() {
        let r = SbomRegistry::new();
        assert!(r.is_empty());
        r.register("x", "1", SbomFormat::CycloneDx, vec![], "ci").unwrap();
        assert_eq!(r.len(), 1);
    }

    #[test]
    fn lookup_unknown_returns_none() {
        let r = SbomRegistry::new();
        assert!(r.get(Uuid::now_v7()).is_none());
    }

    #[test]
    fn many_components_aggregated() {
        let r = SbomRegistry::new();
        let comps: Vec<Component> = (0..50).map(|i| comp(&format!("p{i}"), &format!("c{i}"), "1")).collect();
        let s = r
            .register("x", "1", SbomFormat::Spdx, comps, "ci")
            .unwrap();
        assert_eq!(s.components.len(), 50);
    }
}
