/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAethelredCallback } from './IAethelredCallback.js';
export type { IAethelredTEE } from './IAethelredTEE.js';