{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ include "aethelred-validator.namespace" . }}
  labels:
    {{- include "aethelred-validator.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    {{- toYaml .Values.secretProviderClass.parameters | nindent 4 }}
{{- end }}
