replicaCount: 5
serviceAccount:
  name: aethelred-validator
network:
  chainID: aethelred-mainnet-1
validator:
  image:
    tag: v0.1.0-rc.0
  env:
    logLevel: info
  resources:
    requests:
      cpu: "32"
      memory: 128Gi
      ephemeralStorage: 500Gi
    limits:
      cpu: "64"
      memory: 256Gi
      ephemeralStorage: 1Ti
teeWorker:
  image:
    tag: v0.1.0-rc.0
zkmlProver:
  image:
    tag: v0.1.0-rc.0
service:
  rpc:
    enabled: false
    type: ClusterIP
persistence:
  size: 2Ti
serviceMonitor:
  enabled: true
networkPolicy:
  enabled: true
podDisruptionBudget:
  minAvailable: 3
secretProviderClass:
  enabled: true
  provider: aws
  name: aethelred-validator-spc
  parameters:
    region: me-central-1
    objects: |
      - objectName: /aethelred/mainnet/validator
        objectType: secretsmanager
      - objectName: /aethelred/mainnet/tee
        objectType: secretsmanager
