# Aethelred Node Dockerfile
FROM golang:1.25.12-alpine@sha256:56961d79ea8129efddcc0b8643fd8a5416b4e6228cfd477e3fd61deb2672c587 AS builder

RUN apk add --no-cache make git gcc musl-dev

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN make build

FROM alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

RUN apk add --no-cache ca-certificates curl

COPY --from=builder /app/build/aethelredd /usr/local/bin/

EXPOSE 26657 26656 1317 9090 9091

ENTRYPOINT ["aethelredd"]
CMD ["start"]
