# Aethelred Node Dockerfile
FROM golang:1.21-alpine AS builder

RUN apk add --no-cache make git gcc musl-dev

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN make build

FROM alpine:3.19

RUN apk add --no-cache ca-certificates curl

COPY --from=builder /app/build/aethelredd /usr/local/bin/

EXPOSE 26657 26656 1317 9090 9091

ENTRYPOINT ["aethelredd"]
CMD ["start"]
