from __future__ import annotations

import json
import pathlib
import unittest

from cruzible_sdk import (
    bytes_to_hex,
    compute_canonical_delegation_payload,
    compute_canonical_reward_payload,
    compute_canonical_validator_payload,
    compute_delegation_registry_root,
    compute_eligible_universe_hash,
    compute_selection_policy_hash,
    compute_stake_snapshot_hash,
    compute_staker_registry_root,
    compute_validator_set_hash,
    delegation_input_from_mapping,
    reward_input_from_mapping,
    selection_config_from_mapping,
    staker_from_mapping,
    validator_from_mapping,
)


ROOT = pathlib.Path(__file__).resolve().parents[3]


def read_json(relative_path: str) -> dict:
    return json.loads((ROOT / relative_path).read_text())


def try_read_json(relative_path: str) -> dict | None:
    p = ROOT / relative_path
    if not p.exists():
        return None
    return json.loads(p.read_text())


def has_expected_values(expected: dict | None) -> bool:
    """Return True if the expected dict has at least one non-null hash string."""
    if not expected:
        return False
    return any(
        isinstance(v, str) and k != "_note"
        for k, v in expected.items()
    )


class DefaultConformanceTests(unittest.TestCase):
    """Conformance tests against the default (canonical) test vectors."""

    def test_validator_selection(self) -> None:
        vector = read_json("test-vectors/validator-selection/default.json")
        validators = [validator_from_mapping(item) for item in vector["input"]["validators"]]
        config = selection_config_from_mapping(vector["input"]["config"])

        validator_set_hash = bytes_to_hex(
            compute_validator_set_hash(vector["input"]["epoch"], validators)
        )
        policy_hash = bytes_to_hex(compute_selection_policy_hash(config))
        universe_hash = bytes_to_hex(
            compute_eligible_universe_hash(vector["input"]["eligible_addresses"])
        )
        validator_payload = bytes_to_hex(
            compute_canonical_validator_payload(
                vector["input"]["epoch"],
                validators,
                config,
                vector["input"]["eligible_addresses"],
            )
        )

        self.assertEqual(validator_set_hash, vector["expected"]["validator_set_hash"])
        self.assertEqual(policy_hash, vector["expected"]["policy_hash"])
        self.assertEqual(universe_hash, vector["expected"]["universe_hash"])
        self.assertEqual(validator_payload, vector["expected"]["payload_hex"])

    def test_reward_payload(self) -> None:
        vector = read_json("test-vectors/reward/default.json")
        stakers = [staker_from_mapping(item) for item in vector["input"]["staker_stakes"]]

        stake_snapshot_hash = bytes_to_hex(
            compute_stake_snapshot_hash(vector["input"]["epoch"], stakers)
        )
        staker_registry_root = bytes_to_hex(compute_staker_registry_root(stakers))
        delegation_registry_root = bytes_to_hex(compute_delegation_registry_root(stakers))
        reward_payload = bytes_to_hex(
            compute_canonical_reward_payload(
                reward_input_from_mapping(
                    {
                        "epoch": vector["input"]["epoch"],
                        "total_rewards": vector["input"]["total_rewards"],
                        "merkle_root": vector["input"]["merkle_root"],
                        "protocol_fee": vector["input"]["protocol_fee"],
                        "stake_snapshot_hash": stake_snapshot_hash,
                        "validator_set_hash": vector["input"]["validator_set_hash"],
                        "staker_registry_root": staker_registry_root,
                        "delegation_registry_root": delegation_registry_root,
                    }
                )
            )
        )

        self.assertEqual(stake_snapshot_hash, vector["expected"]["stake_snapshot_hash"])
        self.assertEqual(staker_registry_root, vector["expected"]["staker_registry_root"])
        self.assertEqual(delegation_registry_root, vector["expected"]["delegation_registry_root"])
        self.assertEqual(reward_payload, vector["expected"]["payload_hex"])

    def test_delegation_payload(self) -> None:
        vector = read_json("test-vectors/delegation/default.json")
        delegation_payload = bytes_to_hex(
            compute_canonical_delegation_payload(
                delegation_input_from_mapping(vector["input"])
            )
        )
        self.assertEqual(delegation_payload, vector["expected"]["payload_hex"])


class EdgeCaseConformanceTests(unittest.TestCase):
    """Conformance tests against edge-case test vectors.

    These tests are skipped if the expected hash values have not yet been
    generated by the canonical generator script (generate-expected.ts).
    """

    def test_single_validator(self) -> None:
        vector = try_read_json("test-vectors/edge-cases/single-validator.json")
        if not vector or not has_expected_values(vector.get("expected")):
            self.skipTest("expected values not yet generated")

        inp = vector["input"]
        validators = [validator_from_mapping(v) for v in inp["validators"]]
        config = selection_config_from_mapping(inp["config"])

        self.assertEqual(
            bytes_to_hex(compute_validator_set_hash(inp["epoch"], validators)),
            vector["expected"]["validator_set_hash"],
        )
        self.assertEqual(
            bytes_to_hex(compute_selection_policy_hash(config)),
            vector["expected"]["policy_hash"],
        )
        self.assertEqual(
            bytes_to_hex(compute_eligible_universe_hash(inp["eligible_addresses"])),
            vector["expected"]["universe_hash"],
        )
        self.assertEqual(
            bytes_to_hex(
                compute_canonical_validator_payload(
                    inp["epoch"], validators, config, inp["eligible_addresses"]
                )
            ),
            vector["expected"]["payload_hex"],
        )

    def test_zero_stake(self) -> None:
        vector = try_read_json("test-vectors/edge-cases/zero-stake.json")
        if not vector or not has_expected_values(vector.get("expected")):
            self.skipTest("expected values not yet generated")

        inp = vector["input"]
        stakers = [staker_from_mapping(s) for s in inp["staker_stakes"]]

        self.assertEqual(
            bytes_to_hex(compute_stake_snapshot_hash(inp["epoch"], stakers)),
            vector["expected"]["stake_snapshot_hash"],
        )
        self.assertEqual(
            bytes_to_hex(compute_staker_registry_root(stakers)),
            vector["expected"]["staker_registry_root"],
        )
        self.assertEqual(
            bytes_to_hex(compute_delegation_registry_root(stakers)),
            vector["expected"]["delegation_registry_root"],
        )

    def test_max_uint64_values(self) -> None:
        vector = try_read_json("test-vectors/edge-cases/max-uint64-values.json")
        if not vector or not has_expected_values(vector.get("expected")):
            self.skipTest("expected values not yet generated")

        inp = vector["input"]
        validators = [validator_from_mapping(v) for v in inp["validators"]]
        stakers = [staker_from_mapping(s) for s in inp["staker_stakes"]]

        self.assertEqual(
            bytes_to_hex(compute_validator_set_hash(inp["epoch"], validators)),
            vector["expected"]["validator_set_hash"],
        )
        self.assertEqual(
            bytes_to_hex(compute_stake_snapshot_hash(inp["epoch"], stakers)),
            vector["expected"]["stake_snapshot_hash"],
        )
        self.assertEqual(
            bytes_to_hex(compute_staker_registry_root(stakers)),
            vector["expected"]["staker_registry_root"],
        )
        self.assertEqual(
            bytes_to_hex(compute_delegation_registry_root(stakers)),
            vector["expected"]["delegation_registry_root"],
        )

    def test_empty_tee_key(self) -> None:
        vector = try_read_json("test-vectors/edge-cases/empty-tee-key.json")
        if not vector or not has_expected_values(vector.get("expected")):
            self.skipTest("expected values not yet generated")

        inp = vector["input"]
        validators = [validator_from_mapping(v) for v in inp["validators"]]

        self.assertEqual(
            bytes_to_hex(compute_validator_set_hash(inp["epoch"], validators)),
            vector["expected"]["validator_set_hash"],
        )

    def test_special_addresses(self) -> None:
        vector = try_read_json("test-vectors/edge-cases/special-addresses.json")
        if not vector or not has_expected_values(vector.get("expected")):
            self.skipTest("expected values not yet generated")

        inp = vector["input"]
        validators = [validator_from_mapping(v) for v in inp["validators"]]
        stakers = [staker_from_mapping(s) for s in inp["staker_stakes"]]

        self.assertEqual(
            bytes_to_hex(compute_validator_set_hash(inp["epoch"], validators)),
            vector["expected"]["validator_set_hash"],
        )
        self.assertEqual(
            bytes_to_hex(compute_stake_snapshot_hash(inp["epoch"], stakers)),
            vector["expected"]["stake_snapshot_hash"],
        )
        self.assertEqual(
            bytes_to_hex(compute_staker_registry_root(stakers)),
            vector["expected"]["staker_registry_root"],
        )
        self.assertEqual(
            bytes_to_hex(compute_delegation_registry_root(stakers)),
            vector["expected"]["delegation_registry_root"],
        )

    def test_max_validators(self) -> None:
        vector = try_read_json("test-vectors/edge-cases/max-validators.json")
        if not vector or not has_expected_values(vector.get("expected")):
            self.skipTest("expected values not yet generated")
        if not isinstance(vector["input"].get("validators"), list):
            self.skipTest("validators not yet generated")

        inp = vector["input"]
        validators = [validator_from_mapping(v) for v in inp["validators"]]

        self.assertEqual(
            bytes_to_hex(compute_validator_set_hash(inp["epoch"], validators)),
            vector["expected"]["validator_set_hash"],
        )


if __name__ == "__main__":
    unittest.main()
