/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'TimelockController', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TimelockController__factory>
getContractFactory(name: 'ERC1967Proxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC1967Proxy__factory>
getContractFactory(name: 'AethelredBridge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AethelredBridge__factory>
getContractFactory(name: 'ITimelockDelaySource', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITimelockDelaySource__factory>
getContractFactory(name: 'AethelredToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AethelredToken__factory>
getContractFactory(name: 'ITokenUpgraderTimelockDelaySource', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITokenUpgraderTimelockDelaySource__factory>
getContractFactory(name: 'AethelredVesting', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AethelredVesting__factory>
getContractFactory(name: 'IVestingUpgraderTimelockDelaySource', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IVestingUpgraderTimelockDelaySource__factory>
getContractFactory(name: 'AutomationCompatibleInterface', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AutomationCompatibleInterface__factory>
getContractFactory(name: 'IInstitutionalStablecoinBridgeMonitor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IInstitutionalStablecoinBridgeMonitor__factory>
getContractFactory(name: 'InstitutionalReserveAutomationKeeper', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InstitutionalReserveAutomationKeeper__factory>
getContractFactory(name: 'IAggregatorV3', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAggregatorV3__factory>
getContractFactory(name: 'IMessageTransmitterV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMessageTransmitterV2__factory>
getContractFactory(name: 'IMintBurnERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMintBurnERC20__factory>
getContractFactory(name: 'ITimelockControllerMinDelay', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITimelockControllerMinDelay__factory>
getContractFactory(name: 'ITokenMessengerV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITokenMessengerV2__factory>
getContractFactory(name: 'InstitutionalStablecoinBridge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InstitutionalStablecoinBridge__factory>
getContractFactory(name: 'IReserveOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReserveOracle__factory>
getContractFactory(name: 'SovereignCircuitBreakerModule', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SovereignCircuitBreakerModule__factory>
getContractFactory(name: 'IInstitutionalBridgeGovernance', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IInstitutionalBridgeGovernance__factory>
getContractFactory(name: 'SovereignGovernanceTimelock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SovereignGovernanceTimelock__factory>
getContractFactory(name: 'IAethelredBridge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAethelredBridge__factory>
getContractFactory(name: 'IAethelredOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAethelredOracle__factory>
getContractFactory(name: 'IAethelredCallback', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAethelredCallback__factory>
getContractFactory(name: 'IAethelredTEE', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAethelredTEE__factory>
getContractFactory(name: 'ISovereignCircuitBreaker', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISovereignCircuitBreaker__factory>
getContractFactory(name: 'MockAggregatorV3', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockAggregatorV3__factory>
getContractFactory(name: 'MockInstitutionalBridgeMonitor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockInstitutionalBridgeMonitor__factory>
getContractFactory(name: 'MockMessageTransmitterV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockMessageTransmitterV2__factory>
getContractFactory(name: 'MockMintableBurnableERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockMintableBurnableERC20__factory>
getContractFactory(name: 'MockTimelockController', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockTimelockController__factory>
getContractFactory(name: 'MockTokenMessengerV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockTokenMessengerV2__factory>
getContractFactory(name: 'Cruzible', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Cruzible__factory>
getContractFactory(name: 'ICruzibleUpgraderTimelockDelaySource', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICruzibleUpgraderTimelockDelaySource__factory>
getContractFactory(name: 'ICruzible', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICruzible__factory>
getContractFactory(name: 'IPlatformVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPlatformVerifier__factory>
getContractFactory(name: 'NitroVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NitroVerifier__factory>
getContractFactory(name: 'SevVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SevVerifier__factory>
getContractFactory(name: 'SgxVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SgxVerifier__factory>
getContractFactory(name: 'IStAETHELUpgraderTimelockDelaySource', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStAETHELUpgraderTimelockDelaySource__factory>
getContractFactory(name: 'StAETHEL', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.StAETHEL__factory>
getContractFactory(name: 'IVaultTEEVerifierUpgraderTimelockDelaySource', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IVaultTEEVerifierUpgraderTimelockDelaySource__factory>
getContractFactory(name: 'VaultTEEVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VaultTEEVerifier__factory>

  getContractAt(name: 'TimelockController', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TimelockController>
getContractAt(name: 'ERC1967Proxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC1967Proxy>
getContractAt(name: 'AethelredBridge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AethelredBridge>
getContractAt(name: 'ITimelockDelaySource', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITimelockDelaySource>
getContractAt(name: 'AethelredToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AethelredToken>
getContractAt(name: 'ITokenUpgraderTimelockDelaySource', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITokenUpgraderTimelockDelaySource>
getContractAt(name: 'AethelredVesting', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AethelredVesting>
getContractAt(name: 'IVestingUpgraderTimelockDelaySource', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IVestingUpgraderTimelockDelaySource>
getContractAt(name: 'AutomationCompatibleInterface', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AutomationCompatibleInterface>
getContractAt(name: 'IInstitutionalStablecoinBridgeMonitor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IInstitutionalStablecoinBridgeMonitor>
getContractAt(name: 'InstitutionalReserveAutomationKeeper', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InstitutionalReserveAutomationKeeper>
getContractAt(name: 'IAggregatorV3', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAggregatorV3>
getContractAt(name: 'IMessageTransmitterV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMessageTransmitterV2>
getContractAt(name: 'IMintBurnERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMintBurnERC20>
getContractAt(name: 'ITimelockControllerMinDelay', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITimelockControllerMinDelay>
getContractAt(name: 'ITokenMessengerV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITokenMessengerV2>
getContractAt(name: 'InstitutionalStablecoinBridge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InstitutionalStablecoinBridge>
getContractAt(name: 'IReserveOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReserveOracle>
getContractAt(name: 'SovereignCircuitBreakerModule', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SovereignCircuitBreakerModule>
getContractAt(name: 'IInstitutionalBridgeGovernance', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IInstitutionalBridgeGovernance>
getContractAt(name: 'SovereignGovernanceTimelock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SovereignGovernanceTimelock>
getContractAt(name: 'IAethelredBridge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAethelredBridge>
getContractAt(name: 'IAethelredOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAethelredOracle>
getContractAt(name: 'IAethelredCallback', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAethelredCallback>
getContractAt(name: 'IAethelredTEE', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAethelredTEE>
getContractAt(name: 'ISovereignCircuitBreaker', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISovereignCircuitBreaker>
getContractAt(name: 'MockAggregatorV3', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockAggregatorV3>
getContractAt(name: 'MockInstitutionalBridgeMonitor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockInstitutionalBridgeMonitor>
getContractAt(name: 'MockMessageTransmitterV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockMessageTransmitterV2>
getContractAt(name: 'MockMintableBurnableERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockMintableBurnableERC20>
getContractAt(name: 'MockTimelockController', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockTimelockController>
getContractAt(name: 'MockTokenMessengerV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockTokenMessengerV2>
getContractAt(name: 'Cruzible', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Cruzible>
getContractAt(name: 'ICruzibleUpgraderTimelockDelaySource', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICruzibleUpgraderTimelockDelaySource>
getContractAt(name: 'ICruzible', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICruzible>
getContractAt(name: 'IPlatformVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPlatformVerifier>
getContractAt(name: 'NitroVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NitroVerifier>
getContractAt(name: 'SevVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SevVerifier>
getContractAt(name: 'SgxVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SgxVerifier>
getContractAt(name: 'IStAETHELUpgraderTimelockDelaySource', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStAETHELUpgraderTimelockDelaySource>
getContractAt(name: 'StAETHEL', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.StAETHEL>
getContractAt(name: 'IVaultTEEVerifierUpgraderTimelockDelaySource', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IVaultTEEVerifierUpgraderTimelockDelaySource>
getContractAt(name: 'VaultTEEVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VaultTEEVerifier>

  deployContract(name: 'TimelockController', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TimelockController>
deployContract(name: 'ERC1967Proxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC1967Proxy>
deployContract(name: 'AethelredBridge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AethelredBridge>
deployContract(name: 'ITimelockDelaySource', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITimelockDelaySource>
deployContract(name: 'AethelredToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AethelredToken>
deployContract(name: 'ITokenUpgraderTimelockDelaySource', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITokenUpgraderTimelockDelaySource>
deployContract(name: 'AethelredVesting', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AethelredVesting>
deployContract(name: 'IVestingUpgraderTimelockDelaySource', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IVestingUpgraderTimelockDelaySource>
deployContract(name: 'AutomationCompatibleInterface', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AutomationCompatibleInterface>
deployContract(name: 'IInstitutionalStablecoinBridgeMonitor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IInstitutionalStablecoinBridgeMonitor>
deployContract(name: 'InstitutionalReserveAutomationKeeper', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InstitutionalReserveAutomationKeeper>
deployContract(name: 'IAggregatorV3', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAggregatorV3>
deployContract(name: 'IMessageTransmitterV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMessageTransmitterV2>
deployContract(name: 'IMintBurnERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMintBurnERC20>
deployContract(name: 'ITimelockControllerMinDelay', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITimelockControllerMinDelay>
deployContract(name: 'ITokenMessengerV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITokenMessengerV2>
deployContract(name: 'InstitutionalStablecoinBridge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InstitutionalStablecoinBridge>
deployContract(name: 'IReserveOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReserveOracle>
deployContract(name: 'SovereignCircuitBreakerModule', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SovereignCircuitBreakerModule>
deployContract(name: 'IInstitutionalBridgeGovernance', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IInstitutionalBridgeGovernance>
deployContract(name: 'SovereignGovernanceTimelock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SovereignGovernanceTimelock>
deployContract(name: 'IAethelredBridge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAethelredBridge>
deployContract(name: 'IAethelredOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAethelredOracle>
deployContract(name: 'IAethelredCallback', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAethelredCallback>
deployContract(name: 'IAethelredTEE', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAethelredTEE>
deployContract(name: 'ISovereignCircuitBreaker', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISovereignCircuitBreaker>
deployContract(name: 'MockAggregatorV3', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAggregatorV3>
deployContract(name: 'MockInstitutionalBridgeMonitor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockInstitutionalBridgeMonitor>
deployContract(name: 'MockMessageTransmitterV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockMessageTransmitterV2>
deployContract(name: 'MockMintableBurnableERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockMintableBurnableERC20>
deployContract(name: 'MockTimelockController', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockTimelockController>
deployContract(name: 'MockTokenMessengerV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockTokenMessengerV2>
deployContract(name: 'Cruzible', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Cruzible>
deployContract(name: 'ICruzibleUpgraderTimelockDelaySource', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICruzibleUpgraderTimelockDelaySource>
deployContract(name: 'ICruzible', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICruzible>
deployContract(name: 'IPlatformVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPlatformVerifier>
deployContract(name: 'NitroVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NitroVerifier>
deployContract(name: 'SevVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SevVerifier>
deployContract(name: 'SgxVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SgxVerifier>
deployContract(name: 'IStAETHELUpgraderTimelockDelaySource', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStAETHELUpgraderTimelockDelaySource>
deployContract(name: 'StAETHEL', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StAETHEL>
deployContract(name: 'IVaultTEEVerifierUpgraderTimelockDelaySource', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IVaultTEEVerifierUpgraderTimelockDelaySource>
deployContract(name: 'VaultTEEVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VaultTEEVerifier>

  deployContract(name: 'TimelockController', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TimelockController>
deployContract(name: 'ERC1967Proxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC1967Proxy>
deployContract(name: 'AethelredBridge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AethelredBridge>
deployContract(name: 'ITimelockDelaySource', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITimelockDelaySource>
deployContract(name: 'AethelredToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AethelredToken>
deployContract(name: 'ITokenUpgraderTimelockDelaySource', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITokenUpgraderTimelockDelaySource>
deployContract(name: 'AethelredVesting', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AethelredVesting>
deployContract(name: 'IVestingUpgraderTimelockDelaySource', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IVestingUpgraderTimelockDelaySource>
deployContract(name: 'AutomationCompatibleInterface', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AutomationCompatibleInterface>
deployContract(name: 'IInstitutionalStablecoinBridgeMonitor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IInstitutionalStablecoinBridgeMonitor>
deployContract(name: 'InstitutionalReserveAutomationKeeper', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InstitutionalReserveAutomationKeeper>
deployContract(name: 'IAggregatorV3', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAggregatorV3>
deployContract(name: 'IMessageTransmitterV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMessageTransmitterV2>
deployContract(name: 'IMintBurnERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMintBurnERC20>
deployContract(name: 'ITimelockControllerMinDelay', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITimelockControllerMinDelay>
deployContract(name: 'ITokenMessengerV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITokenMessengerV2>
deployContract(name: 'InstitutionalStablecoinBridge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InstitutionalStablecoinBridge>
deployContract(name: 'IReserveOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReserveOracle>
deployContract(name: 'SovereignCircuitBreakerModule', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SovereignCircuitBreakerModule>
deployContract(name: 'IInstitutionalBridgeGovernance', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IInstitutionalBridgeGovernance>
deployContract(name: 'SovereignGovernanceTimelock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SovereignGovernanceTimelock>
deployContract(name: 'IAethelredBridge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAethelredBridge>
deployContract(name: 'IAethelredOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAethelredOracle>
deployContract(name: 'IAethelredCallback', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAethelredCallback>
deployContract(name: 'IAethelredTEE', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAethelredTEE>
deployContract(name: 'ISovereignCircuitBreaker', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISovereignCircuitBreaker>
deployContract(name: 'MockAggregatorV3', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAggregatorV3>
deployContract(name: 'MockInstitutionalBridgeMonitor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockInstitutionalBridgeMonitor>
deployContract(name: 'MockMessageTransmitterV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockMessageTransmitterV2>
deployContract(name: 'MockMintableBurnableERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockMintableBurnableERC20>
deployContract(name: 'MockTimelockController', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockTimelockController>
deployContract(name: 'MockTokenMessengerV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockTokenMessengerV2>
deployContract(name: 'Cruzible', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Cruzible>
deployContract(name: 'ICruzibleUpgraderTimelockDelaySource', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICruzibleUpgraderTimelockDelaySource>
deployContract(name: 'ICruzible', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICruzible>
deployContract(name: 'IPlatformVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPlatformVerifier>
deployContract(name: 'NitroVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NitroVerifier>
deployContract(name: 'SevVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SevVerifier>
deployContract(name: 'SgxVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SgxVerifier>
deployContract(name: 'IStAETHELUpgraderTimelockDelaySource', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStAETHELUpgraderTimelockDelaySource>
deployContract(name: 'StAETHEL', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StAETHEL>
deployContract(name: 'IVaultTEEVerifierUpgraderTimelockDelaySource', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IVaultTEEVerifierUpgraderTimelockDelaySource>
deployContract(name: 'VaultTEEVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VaultTEEVerifier>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  