#!/usr/bin/env python3
"""Emit a cross-stack evidence vector: an artifact produced by the Python
demonstration layer that the Go production stack can independently verify.

This closes the "which one is the product?" gap by pinning ONE canonical
evidence format across both stacks. The Go verifier (internal/evidence) reads
this vector and, using only the Go standard library, (1) re-verifies the demo's
Ed25519 batch signature and (2) re-derives the record identity digest — proving
the production stack accepts artifacts generated by the demonstration layer.

The classical (Ed25519, RFC 8032) leg is the cross-stack anchor because it is
interoperable with Go's crypto/ed25519. The post-quantum (XMSS) leg and full
canonical-form reproduction in Go are the remaining unification steps.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import m42_crypto as crypto
import m42_seal as s

OUT = Path(__file__).resolve().parents[1] / "config/pilots/m42/crossstack/seal-vector.json"


def build_vector() -> dict:
    seals = [
        s.build_seal(
            workload="digital-pathology-ai", model_hash="a" * 64, circuit_hash="b" * 64,
            input_value={"slide": i}, output_value={"malignant": (i % 2 == 0)},
            chain_id="aethelred-m42-pilot-1", timestamp="2026-07-11T00:00:00Z",
            nonce=f"xnonce-{i}", platform="sev-snp", zkml_tractable=True, seed_label=f"xjob-{i}")
        for i in range(4)
    ]
    bp = s.anchor_batch(seals, batch_index=101)

    # The exact bytes the validator signed (must match m42_seal.verify_batch).
    commitment = crypto.canonical_bytes({
        "seal_batch_root": bp["seal_batch_root"],
        "attestation_batch_root": bp["attestation_batch_root"],
        "chain_id": bp.get("chain_id"),
        "batch_index": bp.get("batch_index"),
        "seal_count": bp.get("seal_count"),
    })
    ed25519_sig = bp["validator_hybrid_signature"]["ed25519"]

    # One record's canonical identity body (seal_id = sha256(body)).
    seal = seals[0]
    body = crypto.canonical_bytes(s._seal_body(seal))

    return {
        "format": "aethelred-evidence-vector-v1",
        "description": "Python-generated evidence for independent Go verification.",
        "validator_ed25519_pubkey_hex": bp["validator_pubkey"],
        "batch_commitment_hex": commitment.hex(),
        "batch_ed25519_signature_hex": ed25519_sig,
        "seal_id_hex": seal["seal_id"],
        "seal_body_canonical_hex": body.hex(),
    }


def main() -> int:
    vector = build_vector()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(vector, indent=2), encoding="utf-8")

    # Self-check in Python before handing to Go.
    pub = bytes.fromhex(vector["validator_ed25519_pubkey_hex"])
    msg = bytes.fromhex(vector["batch_commitment_hex"])
    sig = bytes.fromhex(vector["batch_ed25519_signature_hex"])
    sig_ok = crypto.ed25519_verify(pub, msg, sig)
    body = bytes.fromhex(vector["seal_body_canonical_hex"])
    digest_ok = crypto.sha256_hex(body) == vector["seal_id_hex"]
    print(f"wrote {OUT}")
    print(f"  ed25519 signature self-check: {sig_ok}")
    print(f"  seal_id digest self-check:    {digest_ok}")
    return 0 if (sig_ok and digest_ok) else 1


if __name__ == "__main__":
    raise SystemExit(main())
