/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStAETHELUpgraderTimelockDelaySource } from './IStAETHELUpgraderTimelockDelaySource.js';
export type { StAETHEL } from './StAETHEL.js';