// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: aethelred/verify/v1/verify.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_RegisterVerifyingKey_FullMethodName = "/aethelred.verify.v1.Msg/RegisterVerifyingKey"
	Msg_RegisterCircuit_FullMethodName      = "/aethelred.verify.v1.Msg/RegisterCircuit"
	Msg_VerifyZKProof_FullMethodName        = "/aethelred.verify.v1.Msg/VerifyZKProof"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg service
type MsgClient interface {
	RegisterVerifyingKey(ctx context.Context, in *MsgRegisterVerifyingKey, opts ...grpc.CallOption) (*MsgRegisterVerifyingKeyResponse, error)
	RegisterCircuit(ctx context.Context, in *MsgRegisterCircuit, opts ...grpc.CallOption) (*MsgRegisterCircuitResponse, error)
	VerifyZKProof(ctx context.Context, in *MsgVerifyZKProof, opts ...grpc.CallOption) (*MsgVerifyZKProofResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterVerifyingKey(ctx context.Context, in *MsgRegisterVerifyingKey, opts ...grpc.CallOption) (*MsgRegisterVerifyingKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterVerifyingKeyResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterVerifyingKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterCircuit(ctx context.Context, in *MsgRegisterCircuit, opts ...grpc.CallOption) (*MsgRegisterCircuitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterCircuitResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterCircuit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) VerifyZKProof(ctx context.Context, in *MsgVerifyZKProof, opts ...grpc.CallOption) (*MsgVerifyZKProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgVerifyZKProofResponse)
	err := c.cc.Invoke(ctx, Msg_VerifyZKProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg service
type MsgServer interface {
	RegisterVerifyingKey(context.Context, *MsgRegisterVerifyingKey) (*MsgRegisterVerifyingKeyResponse, error)
	RegisterCircuit(context.Context, *MsgRegisterCircuit) (*MsgRegisterCircuitResponse, error)
	VerifyZKProof(context.Context, *MsgVerifyZKProof) (*MsgVerifyZKProofResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) RegisterVerifyingKey(context.Context, *MsgRegisterVerifyingKey) (*MsgRegisterVerifyingKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterVerifyingKey not implemented")
}
func (UnimplementedMsgServer) RegisterCircuit(context.Context, *MsgRegisterCircuit) (*MsgRegisterCircuitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCircuit not implemented")
}
func (UnimplementedMsgServer) VerifyZKProof(context.Context, *MsgVerifyZKProof) (*MsgVerifyZKProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyZKProof not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_RegisterVerifyingKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterVerifyingKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterVerifyingKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterVerifyingKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterVerifyingKey(ctx, req.(*MsgRegisterVerifyingKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterCircuit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterCircuit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterCircuit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterCircuit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterCircuit(ctx, req.(*MsgRegisterCircuit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_VerifyZKProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVerifyZKProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VerifyZKProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_VerifyZKProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VerifyZKProof(ctx, req.(*MsgVerifyZKProof))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aethelred.verify.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterVerifyingKey",
			Handler:    _Msg_RegisterVerifyingKey_Handler,
		},
		{
			MethodName: "RegisterCircuit",
			Handler:    _Msg_RegisterCircuit_Handler,
		},
		{
			MethodName: "VerifyZKProof",
			Handler:    _Msg_VerifyZKProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aethelred/verify/v1/verify.proto",
}
