// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: aethelred/seal/v1/seal.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_CreateSeal_FullMethodName = "/aethelred.seal.v1.Msg/CreateSeal"
	Msg_RevokeSeal_FullMethodName = "/aethelred.seal.v1.Msg/RevokeSeal"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the seal module Msg service
type MsgClient interface {
	CreateSeal(ctx context.Context, in *MsgCreateSeal, opts ...grpc.CallOption) (*MsgCreateSealResponse, error)
	RevokeSeal(ctx context.Context, in *MsgRevokeSeal, opts ...grpc.CallOption) (*MsgRevokeSealResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateSeal(ctx context.Context, in *MsgCreateSeal, opts ...grpc.CallOption) (*MsgCreateSealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateSealResponse)
	err := c.cc.Invoke(ctx, Msg_CreateSeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeSeal(ctx context.Context, in *MsgRevokeSeal, opts ...grpc.CallOption) (*MsgRevokeSealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRevokeSealResponse)
	err := c.cc.Invoke(ctx, Msg_RevokeSeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the seal module Msg service
type MsgServer interface {
	CreateSeal(context.Context, *MsgCreateSeal) (*MsgCreateSealResponse, error)
	RevokeSeal(context.Context, *MsgRevokeSeal) (*MsgRevokeSealResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) CreateSeal(context.Context, *MsgCreateSeal) (*MsgCreateSealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSeal not implemented")
}
func (UnimplementedMsgServer) RevokeSeal(context.Context, *MsgRevokeSeal) (*MsgRevokeSealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeSeal not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_CreateSeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSeal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateSeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSeal(ctx, req.(*MsgCreateSeal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeSeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeSeal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeSeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevokeSeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeSeal(ctx, req.(*MsgRevokeSeal))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aethelred.seal.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSeal",
			Handler:    _Msg_CreateSeal_Handler,
		},
		{
			MethodName: "RevokeSeal",
			Handler:    _Msg_RevokeSeal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aethelred/seal/v1/seal.proto",
}

const (
	Query_Seal_FullMethodName         = "/aethelred.seal.v1.Query/Seal"
	Query_Seals_FullMethodName        = "/aethelred.seal.v1.Query/Seals"
	Query_SealsByModel_FullMethodName = "/aethelred.seal.v1.Query/SealsByModel"
	Query_VerifySeal_FullMethodName   = "/aethelred.seal.v1.Query/VerifySeal"
	Query_Params_FullMethodName       = "/aethelred.seal.v1.Query/Params"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query service
type QueryClient interface {
	Seal(ctx context.Context, in *QuerySealRequest, opts ...grpc.CallOption) (*QuerySealResponse, error)
	Seals(ctx context.Context, in *QuerySealsRequest, opts ...grpc.CallOption) (*QuerySealsResponse, error)
	SealsByModel(ctx context.Context, in *QuerySealsByModelRequest, opts ...grpc.CallOption) (*QuerySealsByModelResponse, error)
	VerifySeal(ctx context.Context, in *QueryVerifySealRequest, opts ...grpc.CallOption) (*QueryVerifySealResponse, error)
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Seal(ctx context.Context, in *QuerySealRequest, opts ...grpc.CallOption) (*QuerySealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySealResponse)
	err := c.cc.Invoke(ctx, Query_Seal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Seals(ctx context.Context, in *QuerySealsRequest, opts ...grpc.CallOption) (*QuerySealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySealsResponse)
	err := c.cc.Invoke(ctx, Query_Seals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SealsByModel(ctx context.Context, in *QuerySealsByModelRequest, opts ...grpc.CallOption) (*QuerySealsByModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySealsByModelResponse)
	err := c.cc.Invoke(ctx, Query_SealsByModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerifySeal(ctx context.Context, in *QueryVerifySealRequest, opts ...grpc.CallOption) (*QueryVerifySealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVerifySealResponse)
	err := c.cc.Invoke(ctx, Query_VerifySeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query service
type QueryServer interface {
	Seal(context.Context, *QuerySealRequest) (*QuerySealResponse, error)
	Seals(context.Context, *QuerySealsRequest) (*QuerySealsResponse, error)
	SealsByModel(context.Context, *QuerySealsByModelRequest) (*QuerySealsByModelResponse, error)
	VerifySeal(context.Context, *QueryVerifySealRequest) (*QueryVerifySealResponse, error)
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Seal(context.Context, *QuerySealRequest) (*QuerySealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Seal not implemented")
}
func (UnimplementedQueryServer) Seals(context.Context, *QuerySealsRequest) (*QuerySealsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Seals not implemented")
}
func (UnimplementedQueryServer) SealsByModel(context.Context, *QuerySealsByModelRequest) (*QuerySealsByModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SealsByModel not implemented")
}
func (UnimplementedQueryServer) VerifySeal(context.Context, *QueryVerifySealRequest) (*QueryVerifySealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySeal not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Seal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Seal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Seal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Seal(ctx, req.(*QuerySealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Seals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Seals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Seals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Seals(ctx, req.(*QuerySealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SealsByModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySealsByModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SealsByModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SealsByModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SealsByModel(ctx, req.(*QuerySealsByModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerifySeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifySealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifySeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VerifySeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifySeal(ctx, req.(*QueryVerifySealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aethelred.seal.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Seal",
			Handler:    _Query_Seal_Handler,
		},
		{
			MethodName: "Seals",
			Handler:    _Query_Seals_Handler,
		},
		{
			MethodName: "SealsByModel",
			Handler:    _Query_SealsByModel_Handler,
		},
		{
			MethodName: "VerifySeal",
			Handler:    _Query_VerifySeal_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aethelred/seal/v1/seal.proto",
}
